name: Mulitline Script Executor
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Welcome Message
        run: |
            echo "Hello World"
            echo "Welcome"
        
